PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX :    <http://steveroggenkamp.com/kycrashdata/>
PREFIX a:   <http://steveroggenkamp.com/kycrashdata/attrs/>
PREFIX counties:   <http://steveroggenkamp.com/kycrashdata/counties/>
PREFIX collman:   <http://steveroggenkamp.com/kycrashdata/collman/>
PREFIX injsev:   <http://steveroggenkamp.com/kycrashdata/injsev/>
PREFIX lgtcond:   <http://steveroggenkamp.com/kycrashdata/lgtcond/>
PREFIX lnduse:   <http://steveroggenkamp.com/kycrashdata/lnduse/>
PREFIX persontype: <http://steveroggenkamp.com/kycrashdata/persontype/>
PREFIX rdcond:   <http://steveroggenkamp.com/kycrashdata/rdcond/>
PREFIX rdsurf:   <http://steveroggenkamp.com/kycrashdata/rdsurf/>
PREFIX unittype: <http://steveroggenkamp.com/kycrashdata/unittype/>
PREFIX wxcond:   <http://steveroggenkamp.com/kycrashdata/wxcond/>

SELECT ?person ?age ?gender ?injlocdesc 
WHERE { ?crash  <a:involvedUnit> ?unit .
        ?unit   <a:involvesPerson> ?person .
	?person <a:description>    "BICYCLIST" .
	?person <a:personAge>      ?age .
	?person <a:gender>         ?gender .
	?person <a:injurySeverity> ?injsev .
	?injsev <a:description>    "FATAL" .
	?person <a:injuryLocation> ?injloc .
	?injloc <a:description>    ?injlocdesc .
 }
GROUP By ?person
ORDER BY ?person
